services:
 app:
  container_name: go-api
  build:
   context: .
   dockerfile: Dockerfile
  image: go-api
  ports:
   - 9090:9090
  env_file:
   - .env
  depends_on:
   mysql:
    condition: service_healthy
  networks:
   - go-network

 mysql:
  container_name: go-mysql
  image: mysql:8.0
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_USER=user
   - MYSQL_PASSWORD=password
  volumes:
   - dbdata:/var/lib/mysql
  networks:
   - go-network

volumes:
 dbdata:

networks:
 go-network:
  driver: bridge
